# configure some default settings
[default]
sqlalchemy_database_uri = "sqlite:///rectangle.sqlite"
sqlalchemy_track_modifications = false

# configure the development environment settings
[development]
flask_debug = true
extensions = ["flask_debugtoolbar:DebugToolbarExtension"]
debug_tb_enabled = true
debug_tb_intercept_redirects = false
debug_tb_profiler_enabled = true
debug_tb_template_editor_enabled = true

# development datatabase settings
sqlalchemy_echo = false
sqlalchemy_record_queries = true

# set the development logging level
logging_level = "DEBUG"

# configure the production environment settings
[production]
flask_debug = false

# production datatabase settings
sqlalchemy_echo = false
sqlalchemy_record_queries = false

# set the production logging level
logging_level = "INFO"

